apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-eks-demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: secure-eks-demo

  template:
    metadata:
      labels:
        app: secure-eks-demo

    spec:
      serviceAccountName: secure-eks-demo

      securityContext:
        runAsNonRoot: true

      containers:
        - name: app
          image: ECR_IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
